name: bayes_losvd

channels:
  - conda-forge

dependencies:
  - python=3.12

  # Core numerical/data stack
  - numpy
  - scipy
  - pandas
  - xarray
  - h5py

  # Bayesian analysis
  - arviz

  # Astronomy
  - astropy

  # Plotting and visualization
  - matplotlib
  - plotly

  # Analysis / utilities
  - scikit-learn
  - tqdm
  - toml

  # Interactive environment
  - ipython
  - ipykernel
  - ipywidgets

  - pip
  - pip:
      - "jax[cuda13]"
      - numpyro
      - powerbin==1.1.9