# =============================================================================
# Configuration file defining the available Numpyro codes and extra parameters
#------------------------------------------------------------------------------
#
# Format:
#
# [<code acronym>]
# codefile = < Numpyro's code file in 'scripts/models' directory
# <any other additional parameter needed>
# =============================================================================

[SP]
codefile = "bayes_losvd_model_SP.py"

[GP]
codefile = "bayes_losvd_model_GP.py"

