# =============================================================================
# Configuration file defining the available templates
#------------------------------------------------------------------------------
#
# Format:
#
# [<template acronym>]
# read_file = < python code that reads the data> It should be placed in the 'config_files/templates' directory
# lsf_file  = < Line-Spread Function file to be used with that template library>  It should be placed in the 'config_files/templates' directory
# =============================================================================

[EMILES_SSP]
read_file = 'EMILES_SSP.py'
lsf_file  = 'EMILES_SSP.lsf'

[MILES_SSP]
read_file = 'MILES_SSP.py'
lsf_file  = 'MILES_SSP.lsf'

[sMILES_SSP]
read_file = 'sMILES_SSP.py'
lsf_file  = 'sMILES_SSP.lsf'

[MILES_Stars]
read_file = 'MILES_Stars.py'
lsf_file  = 'MILES_Stars.lsf'

[XSL_Stars]
read_file = 'XSL_Stars.py'
lsf_file  = 'XSL_Stars.lsf'

[SINFONI]
read_file = 'SINFONI.py'
lsf_file  = 'SINFONI.lsf'

[MILES_mid]
read_file = 'MILES_SSP.py'
lsf_file  = 'MILES_SSP.lsf'

[MILES_small]
read_file = 'MILES_SSP.py'
lsf_file  = 'MILES_SSP.lsf'

[sMILES_mid]
read_file = 'sMILES_SSP.py'
lsf_file  = 'sMILES_SSP.lsf'
