python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR10-Border0_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR10-Border0_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR10-Border1_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR10-Border1_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR10-Border2_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR10-Border2_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR10-Border3_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR10-Border3_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR10-Border4_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR10-Border4_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR25-Border0_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR25-Border0_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR25-Border1_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR25-Border1_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR25-Border2_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR25-Border2_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR25-Border3_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR25-Border3_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR25-Border4_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR25-Border4_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR50-Border0_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR50-Border0_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR50-Border1_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR50-Border1_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR50-Border2_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR50-Border2_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR50-Border3_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR50-Border3_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR50-Border4_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR50-Border4_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR100-Border0_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR100-Border0_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR100-Border1_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR100-Border1_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR100-Border2_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR100-Border2_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR100-Border3_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR100-Border3_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR100-Border4_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR100-Border4_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR200-Border0_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR200-Border0_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR200-Border1_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR200-Border1_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR200-Border2_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR200-Border2_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR200-Border3_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR200-Border3_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR200-Border4_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Mixed_SNR200-Border4_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR10-Border0_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR10-Border0_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR10-Border1_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR10-Border1_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR10-Border2_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR10-Border2_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR10-Border3_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR10-Border3_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR10-Border4_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR10-Border4_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR25-Border0_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR25-Border0_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR25-Border1_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR25-Border1_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR25-Border2_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR25-Border2_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR25-Border3_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR25-Border3_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR25-Border4_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR25-Border4_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR50-Border0_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR50-Border0_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR50-Border1_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR50-Border1_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR50-Border2_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR50-Border2_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR50-Border3_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR50-Border3_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR50-Border4_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR50-Border4_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR100-Border0_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR100-Border0_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR100-Border1_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR100-Border1_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR100-Border2_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR100-Border2_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR100-Border3_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR100-Border3_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR100-Border4_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR100-Border4_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR200-Border0_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR200-Border0_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR200-Border1_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR200-Border1_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR200-Border2_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR200-Border2_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR200-Border3_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR200-Border3_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR200-Border4_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Old_SNR200-Border4_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR10-Border0_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR10-Border0_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR10-Border1_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR10-Border1_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR10-Border2_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR10-Border2_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR10-Border3_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR10-Border3_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR10-Border4_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR10-Border4_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR25-Border0_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR25-Border0_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR25-Border1_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR25-Border1_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR25-Border2_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR25-Border2_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR25-Border3_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR25-Border3_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR25-Border4_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR25-Border4_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR50-Border0_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR50-Border0_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR50-Border1_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR50-Border1_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR50-Border2_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR50-Border2_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR50-Border3_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR50-Border3_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR50-Border4_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR50-Border4_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR100-Border0_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR100-Border0_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR100-Border1_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR100-Border1_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR100-Border2_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR100-Border2_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR100-Border3_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR100-Border3_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR100-Border4_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR100-Border4_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR200-Border0_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR200-Border0_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR200-Border1_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR200-Border1_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR200-Border2_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR200-Border2_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR200-Border3_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR200-Border3_penalised.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR200-Border4_free.hdf5
python bayes-losvd_run.py -c 3 -i 1500 -f ../preproc_data/testcase_Marie1_Young_SNR200-Border4_penalised.hdf5