python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Old_SNR100-NPCA10.hdf5     -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Old_SNR100-NPCA2.hdf5      -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Old_SNR100-NPCA5.hdf5      -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Old_SNR50-NPCA10.hdf5      -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Old_SNR50-NPCA2.hdf5       -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Old_SNR50-NPCA5.hdf5       -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Young_SNR100-NPCA10.hdf5   -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Young_SNR100-NPCA2.hdf5    -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Young_SNR100-NPCA5.hdf5    -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Young_SNR50-NPCA10.hdf5    -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Young_SNR50-NPCA2.hdf5     -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Young_SNR50-NPCA5.hdf5     -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Mixed_SNR100-NPCA10.hdf5   -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Mixed_SNR100-NPCA2.hdf5    -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Mixed_SNR100-NPCA5.hdf5    -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Mixed_SNR50-NPCA10.hdf5    -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Mixed_SNR50-NPCA2.hdf5     -i 2500 -c 3 -p 1
python bayes-losvd_run.py -f  ../preproc_data/testcase_Gaussian_Mixed_SNR50-NPCA5.hdf5     -i 2500 -c 3 -p 1
